{% set version = "1.4.1" %}

package:
  name: featuretools
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/f/featuretools/featuretools-{{ version }}.tar.gz
  sha256: d820fe9bb9d4a4459931c2f984c49355b9243fc8a096f1406ac50c2354599fc1

build:
  entry_points:
    - featuretools = featuretools.__main__:cli
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python >=3.7.*
  run:
    - click >=7.0.0
    - cloudpickle >=1.5.0
    - dask >=2021.10.0
    - distributed >=2021.10.0
    - numpy >=1.21.0
    - pandas >=1.3.0,<1.4.0
    - psutil >=5.6.6
    - python >=3.7.*
    - scipy >=1.3.3
    - tqdm >=4.32.0
    - woodwork >=0.8.1,<0.12.0


test:
  commands:
    - featuretools --help
    - featuretools info
    - featuretools list-primitives
    - pytest -n 2 --pyargs featuretools
  imports:
    - featuretools
  requires:
    - boto3 >=1.17.46
    - composeml >=0.8.0
    - graphviz !=2.47.2
    - python-graphviz >=0.8.4
    - moto >=1.3.15
    - pip >=21.3.1
    - pyarrow >=3.0.0
    - pympler >=0.8
    - pytest >=5.2.0
    - pytest-cov >=2.6.1
    - pytest-xdist >=1.26.1
    - pytest >=5.2.0
    - smart_open >=5.0.0
    - urllib3 >=1.26.5
    - wheel >=0.33.1

  source_files:
    - featuretools/*

about:
  doc_url: https://featuretools.alteryx.com
  dev_url: https://github.com/alteryx/Featuretools
  home: https://www.featuretools.com
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: a framework for automated feature engineering
  description: |
    Featuretools is a framework to perform automated feature engineering. 
    It excels at transforming temporal and relational datasets into 
    feature matrices for machine learning.

extra:
  recipe-maintainers:
    - rwedge
    - tamargrey
    - thehomebrewnerd
    - jeff-hernandez
    - gsheni
    - dvreed77
