{% set version = "1.31.0" %}
{% set name = "featuretools" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 01bfb17fcc1715b4c3623c7bc94a8982122c4a0fa03350ed478601bb81f90155

build:
  # According to https://github.com/AnacondaRecipes/woodwork-feedstock/pull/8#issuecomment-3433122201
  # this package cannot be build for python 3.13
  skip: true  # [py<39 or py>312]
  number: 0
  script: {{ PYTHON }} -m pip install --no-deps --no-build-isolation -vv .

requirements:
  host:
    - pip
    - python
    - wheel
    - setuptools >=61.0.0
  run:
    - cloudpickle >=1.5.0
    - holidays >=0.17
    - numpy >=1.25.0
    - packaging >=20.0
    - pandas >=2.0.0
    - psutil >=5.7.0
    - python
    - scipy >=1.10.0
    - tqdm >=4.66.3
    - woodwork >=0.28.0 # [py<313]
  run_constrained:
    - autonormalize >=2.0.1
    - dask-core >=2023.2.0
    - distributed >=2023.2.0
    - nlp-primitives >=2.12.0
    - premium-primitives >=0.0.3
    - featuretools-sklearn-transformer >=1.0.0
    - featuretools_sql >=0.0.1
    - psycopg2-binary >=2.9.3
    - featuretools-tsfresh-primitives >=1.0.0

{% set ignore_tests = [
  "--ignore=featuretools/tests/computational_backend/test_calculate_feature_matrix.py",
  "--ignore=featuretools/tests/synthesis/test_dfs_method.py"
]%}
{% set ignore_tests_win = [
  "--deselect=featuretools/tests/primitive_tests/transform_primitive_tests/test_savgol_filter.py::TestSavgolFilter::test_nans",
  "--deselect=featuretools/tests/entityset_tests/test_plotting.py::test_saving_png_file",
  "--deselect=featuretools/tests/primitive_tests/test_feature_visualizer.py::test_saving_png_file",
  "--deselect=featuretools/tests/primitive_tests/test_feature_visualizer.py::test_html_symbols"
]%}
test:
  source_files:
    - featuretools
    - pyproject.toml
  commands:
    # docker-py has an exact pinning for pywin32 that cause pip check to fail.
    - pip check  # [not win]
    #test_nans fails with Intel MKL, so openblas is used
    - pytest --pyargs featuretools/tests -v {{ ignore_tests | join(" ")}} {{ ignore_tests_win | join(" ")}}  # [win]
    - pytest --pyargs featuretools/tests -v {{ ignore_tests | join(" ")}} # [not win]
  imports:
    - featuretools
    - featuretools.computational_backends
    - featuretools.demo
    - featuretools.entityset
    - featuretools.feature_base
    - featuretools.feature_discovery
    - featuretools.primitives
    - featuretools.selection
    - featuretools.synthesis
    - featuretools.utils
  requires:
    - pip
    - boto3 >=1.34.32
    - composeml >=0.8.0
    - graphviz >=0.8.4
    - moto >=5.0.0
    - pyarrow >=14.0.1
    - pympler >=0.8
    - pytest >=7.1.2
    - pytest-timeout >=2.1.0
    - pytest-xdist >=2.5.0
    - python-graphviz >=0.8.4
    - smart_open >=5.0.0
    - distributed >=2023.2.0
    - openblas  # [not win]
    - urllib3 >=1.26.18

about:
  doc_url: https://featuretools.alteryx.com
  dev_url: https://github.com/alteryx/Featuretools
  home: https://featuretools.alteryx.com
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: a framework for automated feature engineering
  description: |
    Featuretools is a framework to perform automated feature engineering.
    It excels at transforming temporal and relational datasets into
    feature matrices for machine learning.

extra:
  recipe-maintainers:
    - stefaniesmith
    - sbadithe
    - ozzieD
    - machineAYX
    - rwedge
    - tamargrey
    - thehomebrewnerd
    - jeff-hernandez
    - gsheni
    - dvreed77
