travis:
  secure:
    BINSTAR_TOKEN: rK96R+dEUEMpcmOuzt0ktYBslEkeQ1rxwRmphxuqJwLpUmfCYcTKoHEr4AiIJrsI/D2HaqKKQDqbJE2kkJvX9oXSAXER0PRRdIODuBy9SdxJxAkdDWCW5ULd0kP4HDg4fY0H1fAn2udMtCclQxK9ZQmIgzP4ZQ7vPq/IRV1dg00Pm2kd7s7osW5sDfFuFzUAWev00AYg40TfrULCp1+mdpp1xnMZqLBhtXCvKkcp01T6ZVpUs4g9mXVk/ytQ6hmFzF6Zgy4x4C6Oi1vz2AEJD0ouSXXaat8lnfc0y026zc8ofefgMh0FymLq3NgTPlxr6ud0c74YgFvNTtI2uiJTp/gfnHcUNywYIQMEGCTvqIG08PDW5qdkTr0JIWnVUMg9hrSckqOyMBb8TSCydyWsqs160kJS14RHmUloVGFfR17VRq9qjUzs6EYwoUDjxzfJQ6nPcyjbG+mzm3JmtVstjHt2DsCF7YJcMMWPHArOHA5iFGqXaF4GRQWzjp3imV7k7eTp5W8qgkVhqzfqpvZskUpRjdaPtpiW7Yc0p7fKDOwg+F2KNIYRioohcaykrc88ZhcIzp8EIEm9+wlnrZVx8dAKyhAbSrxV26poNm1UMwaR0Zzsc1Qaqvt+qBbjIcZvE5sKilrV0xZ9o+Fl9V0b+qtVdpni+6GsbXH9vWNpBqM=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
