travis:
  secure:
    BINSTAR_TOKEN: sI89rIoWsAfQhNvwBRTt/bfcyFvBpWhXDNHLWkjTsEX7I4pH2siKpvVH6OxI09IZbYs2CwLlXi1w5ZTtNg/XFkkvY2at1rgbZ5ULyQ/nOZr5fEZbIgXIM4rQHygBswinrbRDgLfTLNuhLj/xZEx68PZ3AssX77vDdvOwyKvRCgC4roIsfxdBmmaL1mFc6AS7pEGeIX4xj7wYULGz3HNKsOR/C9Lqb6rFCm7VuehK3gY6R4YYYH9R8AvdKGdLB44lKtG9t5115OXLEwWuK+r+yZr+iV+nMrgUN3hp8aXPgxScQBm7GRE8l3TVwfcxjZYdmBwWZ80oR5H85DPJ8Z7fD6N29UXQq9xPL0SSp0Da0Qdq1FJkHLqRjMkwWOuDYenNzogrRRM6R525hwlK47K6lHlxgvwEY12sbJY7zC/JPZnkZRmXblTj55Dii7pCNy/gPkGMb6VqS69WaM+CP1JWa1t5IMCg69dYz5rfr6mlRju+jVA+I5dAlnnzHG0HoqJdyfXTeVCDbdoHG9jKRmdkS02dYjC9qLNTWz8qQ1OmCY1BzthXD46ePYMdO+CvdAJr7OL+dt3V72Uzw/KnDG2LHLERb177R4xAl+YjqfU9YiSl7BICmRXsrFtBzFv1w5zxsrimtoQadXgdQGo8p/V8rTv5n7xjrhQ3QqHwrGkAKUg=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
